// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = 'Astro Blog';
export const SITE_DESCRIPTION = 'Welcome to my website!';
export const SITE_URL = 'https://undefinedconcept.github.io';
export const SITE_BASE = '/330docs';

// Site links for the navigation menu ===============================
type sitelinks =
  | { href: string; label: string, class?: string } /* internal link with optional CSS className */
  | { label: string; link: string, class?: string } /* external link with optional CSS className */
  | { label: string; auto: true; dir: string }      /* group of autogenerated links from a directory */
  | { label: string; items: sitelinks[] };          /* group of nested site links */

export const SITE_LINKS: sitelinks[] = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'About' },
  {
    label: 'Blog',
    items: [
      { href: '/blog', label: 'All Posts' },
      {
        label: 'First',
        items: [
          { href: '/blog/first/markdown-style-guide', label: 'First Post' },
          { href: '/blog/first/using-md', label: 'Second Post' },
        ],
      },
      { label: 'Second', auto: true, dir: '/blog/second/' },
    ],
  },
  { label: 'GitHub', link: 'http://github.com/UndefinedConcept' },
];
